---
_clone_deps:
  git:
    apt:
      [git]
    dnf_yum:
      [git]
    pkg:
      [git]
    portage:
      [dev-vcs/git]
  bzr:
    apt:
      bzr
    dnf_yum:
      bzr
    pkg:
      bzr
    portage:
      dev-vcs/bzr
  hg:
    apt:
      mercurial
    dnf_yum:
      mercurial
    pkg:
      mercurial
    portage:
      dev-vcs/mercurial

_repo: "{{ _default_repo | combine(repo) }}"
